### PR TITLE
use RandomAdaptor from commons.math rather than delegate methods by o…

### PR DESCRIPTION
**Pull request by jjfiv**
use RandomAdaptor from commons.math rather than delegate methods by ourselves; fixes missing nextDouble() adapter

### CODE REVIEW

**Comment by etosch** [comment]
Interesting: the variance on the proportions landing in each bucket for RandomRespondent seems to have increased.

**Comment by etosch** [comment]
Can you jack up the number of responses to 500 in https://github.com/SurveyMan/SurveyMan/blob/0533fa47f302b273735cbc064daa7934e7f19fea/src/test/java/edu/umass/cs/surveyman/qc/classifiers/AbstractClassifierTest.java?

**Comment by jjfiv** [comment]
Passes locally now, FWIW

**Comment by etosch** [comment]
woah, this was issue #500

**Pull request merged**
